### ISSUE TITLE
Ajuste no projeto: Erro 500 ao atualizar cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [eliasneri/DsCatalogClient#1]
Caro Elias, tudo bem?

Estou corrigindo o seu trabalho e o mesmo foi aceito, parabéns! Para ficar 100%, peço que você faça o ajuste de tratamento de exceção ao tentar atualizar (PUT) um cliente com código (id) não cadastrado. Está retornando o erro 500, o correto é realizar o mesmo tratamento que você realizou para o GET e o DELETE e retornar o 404 (entity not found).

Assim que você fizer o ajuste por favor, me avise para que eu possa encerrar a issue.

**Comment by eliasneri** [comment]
Bom Dia oliveiralex, 
tudo bem?

Verifiquei o erro que você levantou, efetuei a correção e fiz um novo commit, se puder verificar, eu agradeço.

Obrigado
